<?php

return [
    'enabled' => false,
    'websocket_url' => '',
    'user' => '',
    'password' => '',
    'verify_ssl' => true,
    'read_timeout' => 30,
    'initial_backoff_seconds' => 1,
    'max_backoff_seconds' => 30,
    'user_agent' => 'vendor-neotel-websocket/0.1',
    'log_channel' => null,
    'events_enabled' => true,
    'db_enabled' => true,
    'register_command' => true,
    'load_migrations' => true,
    'register_routes' => true,
    'api_prefix' => 'api/neotel-websocket',
    'status_enabled' => env('NEOTEL_STATUS_ENABLED', false),
    'status_route_enabled' => env('NEOTEL_STATUS_ROUTE_ENABLED', false),
    'status_route_middleware' => [],
    'status_cache_key' => env('NEOTEL_STATUS_CACHE_KEY', 'neotel:listener:status'),
    'status_cache_ttl_seconds' => env('NEOTEL_STATUS_CACHE_TTL_SECONDS', 120),
];
